# Generated by Django 6.1 on 2026-08-19 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('costo_compra', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('iva', models.FloatField()),
                ('total', models.FloatField()),
                ('estatus', models.CharField(choices=[('Procesada', 'Procesada'), ('Cancelada', 'Cancelada')], default='Procesada', max_length=20)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.inventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
